### ISSUE TITLE
Time Clock "Time" size

### ISSUE THREAD

**Issue by rcasad** [Treverr/inSparkle#41]
Current time displayed on CICO screen needs to be enlarged for better viewing, especially for iPad.

**Comment by Treverr** [comment]
![screen shot 2015-12-14 at 12 14 32 pm](https://cloud.githubusercontent.com/assets/5624521/11787914/43f80344-a25c-11e5-9881-282d90576fd8.png)

I am kind of limited with how big i can make it, since this will be a iPhone and iPad app. I would probably need to make different screens to enlarge it properly.

**Comment by rcasad** [comment]
The fix can come down the line. Its just almost impossible to see on this smaller iPad when mounted on a wall.
